# Generated by Django 5.0.4 on 2024-04-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_favoriteitem_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='items',
        ),
        migrations.AddField(
            model_name='favorite',
            name='items',
            field=models.ManyToManyField(to='core.favoriteitem'),
        ),
    ]
