# Generated by Django 5.0.4 on 2024-04-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_favorite_items_favorite_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='category',
            field=models.CharField(choices=[('mens', 'Men'), ('women', 'Women'), ('kids', 'Kids')], max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('mens', 'Men'), ('women', 'Women'), ('kids', 'Kids')], max_length=10),
        ),
    ]
